<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ApplicationIcon>Assets/AvantimeConnect.ico</ApplicationIcon>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets/AvantimeConnect.ico" />
    <ProjectReference Include="..\AvantimeConnect.Core\AvantimeConnect.Core.csproj" />
  </ItemGroup>
</Project>
